// models/session.model.js

import mongoose from 'mongoose';

const sessionSchema = new mongoose.Schema({
  therapist: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  startTime: {
    type: Date,
    required: true,
  },
  endTime: {
    type: Date,
    required: true,
  },
  status: {
    type: String,
    enum: ['scheduled', 'ongoing', 'completed', 'cancelled', 'missed'],
    default: 'scheduled',
  },
  durationMinutes: {
    type: Number,
    required: true,
  },
  meetingLink: {
    type: String, // e.g., generated by Twilio Room or Agora Channel
    default: null,
  },
  recordingUrl: {
    type: String,
    default: null,
  },
  notes: {
    type: String,
    default: '',
  },
}, {
  timestamps: true,
});

export default mongoose.model('Session', sessionSchema);